### ISSUE TITLE
JavaScript  4.7.1 -breaks blockly plus

### ISSUE THREAD

**Issue by DutchmanNL** [excal-foley/ioBroker.blockly-plus#5]
many blockly scripts are affected. i get the error "cannot extract blockly code".
shows no blockly code or messed up code after update.

flag button throws message blocks are not connected properly.

See : https://github.com/ioBroker/ioBroker.javascript/issues/639

**Comment by backfisch88** [comment]
Same in 4.7.2

**Comment by DutchmanNL** [comment]
issue open for to long without follow-up, closure
